usersList = []
print("Welcome to Pumapix!")
print("Enter your favorite")
print("Enter a show name:")
a = raw_input()
usersList.append(a)
print("Enter a show name:")
b = raw_input()
usersList.append(b)
print("Enter a show name:")
c = raw_input()
usersList.append(c)
print("Enter a show name:")
d = raw_input()
usersList.append(d)
print("Enter a show name:")
e = raw_input()
usersList.append(e)
print("Ok, here's what you entered:")
print(usersList)
usersList.append("Breaking Bad")
usersList.append("The Wire")
usersList.sort()
number = 1
print("We've added a couple of shows")
for users in usersList:
	print(str(number) + "." + users)
	number = number + 1 
