print("Welcome to the Haiku generator!")
print("Provide the first line of your haiku:")
a = str(raw_input())
print("Provide the second line of your haiku:")
b = str(raw_input())
print("Provide the third line of your haiku:")
c = str(raw_input())
print("What file would you like to write your haiku to?")
myFile = str(raw_input())
print("Done! To view your haiku, type 'cat' and the name of your file at the command line.")
my_File = open((myFile), "a")
my_File.write(a + '\n' + b + '\n' + c + '\n') 
my_File.close()
